print("Welcome to the tip calculator. ")
bill = float(input("What was the total bill? $"))
people = int(input("How many people to split the bill? "))
perc = float(input("What percentage tip would you like to give? 10, 12, or 15? "))
cost_pp = ((bill * (perc/100 + 1)) / people)
print(f"Each person should pay: ${round(cost_pp,2)}")